repos:
-   repo: https://github.com/PyCQA/flake8
    rev:  3.9.2
    hooks:
    -   id: flake8
        name: Lint with flake8
        args: [--count, --ignore=E501, --max-complexity=10, --max-line-length=127, --show-source, --statistics]
-   repo: https://github.com/pre-commit/mirrors-mypy 
    rev:  v1.1.1
    hooks: 
    -   id: mypy
        name: Type checking with mypy
