name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --ignore=E501 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with mypy
      run: |
        pip install mypy==0.940
        pip install types-flask==1.1.6
        mypy ./
